### ISSUE TITLE
ModuleNotFoundError: No module named 'util.distributed'

### ISSUE THREAD

**Issue by hjoonpark** [FuchenUSTC/PointClustering#4]
Can you point me to what/where util module is?
Or is this a file missing in the repo?
Thank you
```

Traceback (most recent call last):
  File "train.py", line 23, in <module>
    import util.multiprocessing as mpu
  File "/nobackup/joon/1_Projects/PointClustering/util/multiprocessing.py", line 12, in <module>
    import util.distributed as du
ModuleNotFoundError: No module named 'util.distributed'
```

**Comment by alien19** [comment]
@hjoonpark @FuchenUSTC  I have the save problem
